board_manager:
  additional_urls:
  - https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
  - https://arduino.esp8266.com/stable/package_esp8266com_index.json
build_cache:
  compilations_before_purge: 10
  ttl: 720h0m0s
daemon:
  port: "50051"
directories:
  data: arduino_cli/data
  downloads: arduino_cli/downloads
  user: arduino_cli/libraries/atmega328/v0.0.1
library:
  enable_unsafe_install: false
logging:
  file: ""
  format: text
  level: trace
metrics:
  addr: :9090
  enabled: true
output:
  no_color: false
sketch:
  always_export_binaries: false
updater:
  enable_notification: false
